import Head from 'next/head'

type Props = React.PropsWithChildren<{
  title?: string
}>

const Layout = ({ title = 'KOOP', children }: Props) => {
  return (
    <div className="max-w-screen-2xl mx-auto my-0">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  )
}

export default Layout
