import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Footer from './Footer'

type Props = React.PropsWithChildren<{
  title?: string
}>

const Layout = ({ title = 'KOOP', children }: Props) => {
  const router = useRouter()
  return (
    <div className="max-w-screen-2xl mx-auto my-0">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="flex justify-center gap-3 ">
          <Link href={'/'}>Home</Link>
          {router.locales &&
            [...router.locales].map((locale) => (
              <Link key={locale} href={router.asPath} locale={locale}>
                {locale === 'bg' ? 'Български' : 'English'}
              </Link>
            ))}
        </div>
      </header>
      {children}
      <Footer />
    </div>
  )
}

export default Layout
