import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { gql } from '@apollo/client'
import styles from '../styles/Home.module.css'
import client from '../server/apollo-client'

type Props = {
  countries: any[]
}

const Home: NextPage<Props> = ({ countries }) => (
  <div className={styles.container}>
    <Head>
      <title>KOOP</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.grid}>
      {countries.map((country: any) => (
        <div key={country.code} className={styles.card}>
          <h3>
            <a href="#country-name" aria-hidden="true" id="country-name" />
            {country.name}
          </h3>
          <p>
            {country.code} -{country.emoji}
          </p>
        </div>
      ))}
    </div>
  </div>
)

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  })

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  }
}

export default Home
